version: '3.1'
services:
  api:
    build: .
    image: xapi
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - './dist:/xapi'
  db:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - './apidata/mariadb:/var/lib/mysql'
      - './data/sqlinstalls:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: gitarre2k
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
